[package]
name = "sds-core"
version = "1.7.1"
license = "MIT"
description = "Synthetic data showcase core library"
repository = "https://github.com/microsoft/synthetic-data-showcase"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
rand = { version = "0.8" }
fnv = { version = "1.0" }
itertools = { version = "0.10" }
lru = { version = "0.7" }
getrandom = { version = "0.2", features = ["js"] }
log = { version = "0.4", features = ["std"] }
csv = { version = "1.1" }
instant = { version = "0.1", features = [ "stdweb", "wasm-bindgen" ] }
pyo3 = { version = "0.16", features = ["extension-module"], optional = true }
rayon = { version = "1.5", optional = true }
serde = { version = "1.0", features = [ "derive", "rc" ] }
serde_json = { version = "1.0" }
statrs = { version = "0.15 "}