[package]
name = "sds-cli"
version = "1.8.0"
license = "MIT"
description = "Command line interface for the sds-core library"
repository = "https://github.com/microsoft/synthetic-data-showcase"
edition = "2018"

[dependencies]
sds-core = { path = "../core", features = ["rayon"] }
log = { version = "0.4" }
env_logger = { version = "0.9" }
structopt = { version = "0.3" }
csv = { version = "1.1" }
statrs = { version = "0.15 "}