[package]
name = "sds-pyo3"
version = "1.8.0"
license = "MIT"
description = "Python bindings for the sds-core library"
repository = "https://github.com/microsoft/synthetic-data-showcase"
edition = "2021"

[lib]
name = "sds"
crate-type = ["cdylib"]

[dependencies]
log = { version = "0.4", features = ["std"] }
csv = { version = "1.1" }
pyo3 = { version = "0.16", features = ["extension-module"] }
sds-core = { path = "../core", features = ["pyo3", "rayon"] }
env_logger = { version = "0.9" }